# Para cambiar el pruerto por el que corre el tomcat, debido a que estaba presentando conflictos por el puerto 8080
#server.port=8093
server:
  port: 8093

# Ejemplo para ver como queda en el archivo "application_2.yml"

#spring.aop.auto=true
#spring.aop.proxy-target-class=false
#spring.messages.always-use-message-format=false
#spring.messages.basename=messages
#spring.messages.cache-seconds=-1
#spring.mvc.dispatch-trace-request=false
#spring.mvc.dispatch-options-request=true
#security.oauth2.resource.prefer-token-info=true
#security.oauth2.resource.service-id=resource
#spring.couchbase.bucket.name=default

#**********************************
#convirtiendo del .properties a .yml
#**********************************
# SPRING PROPERTIES
spring:
#DATASOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/educationsystem?useSSL=false
    username: root
    password: manager1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy


